name:                Parnassus
version:             0.1.0
license:             BSD3
author:              "Jeremy Silver"
maintainer:          "jeremys@nessiness.com"
copyright:           "2018 Jeremy Silver"

# extra-source-files:
# - README.md
# - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.

dependencies:
  - array >=0.5
  - base >=4.7
  - counter >=0.1
  - containers >=0.6
  - data-default >=0.7
  - deepseq >=1.4
  - directory >=1.3
  - Euterpea >=2.1.0
  - filepath >=1.4
  - HCodecs >=0.5.2
  - hmatrix >=0.20
  - log-domain >=0.12
  - monad-loops >=0.4
  - MonadRandom >=0.1
  - mtl >=2.2
  - music-pitch-literal >=1.7
  - parsec >=3.1
  - parsec-class >=1.0
  - parsec3-numbers >=0.1
  - prettify >=1.0
  - process >=1.6
  - QuickCheck >=2.13
  - random >=1.1
  - range >=0.3
  - search-algorithms >=0.3
  - sort >=1.0
  - split >=0.2
  - text >=1.2
  - time >=1.9
  - tuple >=0.3
  - unix >=2.7
  - vector >=0.12
  - vector-space >=0.15
  - WAVE

library:
  source-dirs: .

# executables:
  # sct-exe:
    # main:                Main.hs
    # source-dirs:         app
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    # dependencies:
    # - caucus

tests:
  Parnassus-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Parnassus
    # - QuickCheck >= 2.14
    # - smallcheck >= 1.2
    # - tasty-smallcheck
    # - tasty-quickcheck
    # - tasty-hunit
    # - tasty >= 1.4
